# typed: false
# frozen_string_literal: true

# This file was generated by https://github.com/magnusopera/terrabuild/blob/main/.github/scripts/generate-homebrew-cask
cask "terrabuild" do
    arch arm: "arm64", intel: "x64"

    name     "terrabuild"
    version  "${TERRABUILD_VERSION}"
    homepage "https://terrabuild.io"
    desc     "Seamless CI/CD tool for building and deploying monorepos."
    binary   "terrabuild"

    on_arm do
      url "${TERRABUILD_DARWIN_ARM64_URL}"
      sha256 "${TERRABUILD_DARWIN_ARM64_SHA256}"
    end

    on_intel do
      url "${TERRABUILD_DARWIN_X64_URL}"
      sha256 "${TERRABUILD_DARWIN_X64_SHA256}"
    end

    zap trash: [
        "~/.terrabuild"
    ]

    caveats do
        license "https://raw.githubusercontent.com/magnusopera/terrabuild/main/LICENSE"
    end
end
