# typed: false
# frozen_string_literal: true

# This file was generated by https://github.com/magnusopera/terrabuild/blob/main/.github/scripts/generate-homebrew-cask
cask "terrabuild" do
    name     "terrabuild"
    version  "${TERRABUILD_VERSION}"
    homepage "https://terrabuild.io"
    desc     "Fast and low ceremony build & deploy system for monorepos"
    binary   "terrabuild"

    on_macos do
      if Hardware::CPU.intel?
        url "${TERRABUILD_DARWIN_X64_URL}"
        sha256 "${TERRABUILD_DARWIN_X64_SHA256}"
      end
      if Hardware::CPU.arm?
        url "${TERRABUILD_DARWIN_ARM64_URL}"
        sha256 "${TERRABUILD_DARWIN_ARM64_SHA256}"
      end
    end

    on_linux do
    #   if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    #     url "${TERRABUILD_LINUX_ARM64_URL}"
    #     sha256 "${TERRABUILD_LINUX_ARM64_SHA256}"
    #   end
      if Hardware::CPU.intel?
        url "${TERRABUILD_LINUX_X64_URL}"
        sha256 "${TERRABUILD_LINUX_X64_SHA256}"
      end
    end

    caveats do
        license "https://raw.githubusercontent.com/magnusopera/terrabuild/main/LICENSE"
    end
end
