terrabuild {
  storage = "azureblob"
  sourcecontrol = "github"
}

target build {
  depends_on = [ "^build" ]
}

target dist {
  depends_on = [ "build" ]
}

target publish "toto" {
  depends_on = [ "dist" ]
}

environment release {
  variables {
    configuration = "Release"
    toto = "caca"
  }
}

extension dotnet {
  container = "mcr.microsoft.com/dotnet/sdk:8.0.101"
  parameters {
    configuration = $configuration
  }
}
