
target build {
  depends_on [ "^build" ]
}

target dist {
  depends_on [ "build" ]
}

target docker {
  depends_on [ "dist" ]
}

target push {
  depends_on [ "docker" ]
}

target deploy {
  depends_on [ "push" ]
}

environment debug {
  variables {
    configuration: "Debug"
    secret_message: "tagada"
    workspace: "default"
  }
}

environment release {
  variables {
    configuration: "Release"
    workspace: "default"
  }
}

extension dotnet {
  script "scripts/dotnet.fsx"
  container "mcr.microsoft.com/dotnet/sdk:7.0"
  parameters {
    configuration: $configuration
  }
}

extension terraform {
    script "scripts/terraform.fsx"
    parameters {
      workspace: $workspace
    }
}
