
workspace {
    space = "magnusopera/default"
}

configuration default {
  variables = {
    configuration: "Debug"
    secret_message: "tagada"
    workspace: "default"
  }
}

configuration release {
  variables = {
    configuration: "Release"
    workspace: "default"
  }
}

target build {
  depends_on = [ ^build ]
}

target dist {
  depends_on = [ build ]
}

target docker {
  depends_on = [ dist ]
}

target push {
  depends_on = [ docker ]
}

target deploy {
  depends_on = [ push ]
}

extension @dotnet {
  defaults = {
    configuration: $configuration
  }
}

extension @terraform {
    defaults = {
      workspace: $workspace
    }
}
