
target build {
  depends_on = [ target.^build ]
}

target publish {
  depends_on = [ target.build ]
}

target docker {
  depends_on = [ target.publish
                 target.^publish ]
}

target push {
  depends_on = [ target.docker ]
}
