# comment at top of file

configuration {
    space = "magnusopera/default"
}

target build { # comment at end of line
  depends_on = [ ^build ]
}

# comment in the middle of the file

target dist {
  depends_on = [ build ]
  rebuild = true
}

target dummy

environment release {
  variables = {
    configuration: "Release"
  }
}

environment dummy

extension dotnet {
  container = "mcr.microsoft.com/dotnet/sdk:8.0.101"
  defaults = {
    configuration: $configuration
  }
}

extension docker { }

# multiple comments at the end
# multiple comments at the end

# multiple comments at the end

