# comment at top of file

workspace {
    id = "d7528db2-83e0-4164-8c8e-1e0d6d6357ca"
    ignores = [ "**/node_modules" ]
}

target build { # comment at end of line
  depends_on = [ ^build ]
}

# comment in the middle of the file

target dist {
  depends_on = [ build ]
  rebuild = true
}

target dummy { }

configuration release {
  configuration = "Release"
}

configuration dummy { }

extension dotnet {
  container = "mcr.microsoft.com/dotnet/sdk:8.0.101"
  defaults {
    configuration = configuration
  }
}

extension docker { }

extension npmext {
    container = "node:20"
    script = "scripts/npm.fsx"
}

# multiple comments at the end
# multiple comments at the end

# multiple comments at the end

