configuration {
  storage "azureblob"
  sourcecontrol "github"
}

target build {
  depends_on [ "^build" ]
}

target dist {
  depends_on [ "build" ]
}

environment release {
  variables {
    configuration: "Release"
  }
}

extension dotnet {
  container "mcr.microsoft.com/dotnet/sdk:8.0.101"
  init {
    configuration: $configuration
  }
}

extension docker { }
