
workspace {
    space = "magnusopera/terrabuild"
}

configuration {
    variables = {
        configuration: "Debug"
    }
}

configuration dev {
    variables = {
        configuration: "Release"
    }
}

configuration prod {
    variables = {
        configuration: "Release"
    }
}

target build {
    depends_on = [^build]
}

target test {
    depends_on = [build]
}

target dist {
    depends_on = [build]
}

target publish {
    depends_on = [dist]
}

extension @dotnet {
    container = "mcr.microsoft.com/dotnet/sdk:8.0.302"
    variables = [
        "DOTNET_CLI_TELEMETRY_OPTOUT"
        "DOTNET_NOLOGO"
        "DOTNET_CLI_TELEMETRY_OPTOUT"
    ]
    defaults = {
        configuration: $configuration
    }
}
