
target build {
    depends_on [^build]
}

target test {
    depends_on [build]
}

target dist {
    depends_on [build]
}

target publish {
    depends_on [dist]
}

environment debug {
    variables {
        configuration: "Debug"
    }
}

environment release {
    variables {
        configuration: "Release"
    }
}

extension @dotnet {
    container "mcr.microsoft.com/dotnet/sdk:8.0.201"
    defaults {
        configuration: $configuration
    }
}
