
configuration {
    space = "magnusopera/terrabuild"
}

target build {
    depends_on = [^build]
}

target test {
    depends_on = [build]
}

target dist {
    depends_on = [build]
}

target publish {
    depends_on = [dist]
}

environment default {
    variables = {
        configuration: "Debug"
    }
}

environment release {
    variables = {
        configuration: "Release"
    }
}

extension @dotnet {
    container = "mcr.microsoft.com/dotnet/sdk:8.0.204"
    defaults = {
        configuration: $configuration
    }
}
