name: build

on: push

env:
  TERRABUILD_AZURE_BLOB_STORAGE: ${{ secrets.TERRABUILD_AZURE_BLOB_STORAGE }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write    

    steps:
      - name: Cloning repository
        uses: actions/checkout@v1

      - name: Build
        run: make build

      - name: Dump
        run: env

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: make github-tests

      - name: Upload Terrabuild Debug
        uses: actions/upload-artifact@v2
        with:
          name: Terrabuild Debug
          path: terrabuild.*.json

      - name: Upload Terrabuild Cache
        uses: actions/upload-artifact@v2
        with:
          name: Terrabuild Cache
          path: .terrabuild
