name: prepare-release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.204

      - name: Build & Publish
        run: make dist-all config=Release version=${{github.ref_name}}

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            ./.out/*.zip
            ./.out/*.nupkg
