name: 🚀 Feature

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**
      - chore/**
      - release/**
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setup Tools
        uses: ./.github/actions/setup-tools
        with:
          GITHUB_TOKEN: ${{ github.token }}
          install_dotnet: "true"
          install_node: "true"
          install_pnpm: "true"
          install_fscript: "true"
          install_terrabuild: "true"

      - name: Login to Insights Staging
        env:
          TERRABUILD_API_URL: https://api.staging.magnusopera.io/terrabuild
          TERRABUILD_TOKEN: ${{ secrets.TERRABUILD_TOKEN }}
          TERRABUILD_MASTER_KEY: ${{ secrets.TERRABUILD_MASTER_KEY }}
        run: |
          terrabuild version
          terrabuild login \
            --workspace "edd11090a41b0291301431d0" \
            --token "$TERRABUILD_TOKEN" \
            --masterkey "$TERRABUILD_MASTER_KEY"

      - name: Self Build
        env:
          TERRABUILD_API_URL: https://api.staging.magnusopera.io/terrabuild
        run: |
          echo "# Self Build" >> $GITHUB_STEP_SUMMARY
          make self

      - name: Logout from Insights Staging
        if: always()
        run: terrabuild logout --space "edd11090a41b0291301431d0"

      - name: Create Test Report
        uses: magnusopera/test-reporter@main
        if: always()
        with:
          name: Unit Tests Report
          path: '**/*.trx'
          reporter: dotnet-trx
          fail-on-error: false
          fail-on-empty: false
          use-actions-summary: true

      - name: Self Integration Tests
        run: make smoke-tests terrabuild=$PWD/.out/dotnet/terrabuild

      - name: Include Build Logs
        if: always()
        run: |
          ls -alR > terrabuild-debug.files.txt

          echo "# Self Tests" >> $GITHUB_STEP_SUMMARY
          echo "## basic" >> $GITHUB_STEP_SUMMARY
          cat tests/basic/terrabuild-debug.md >> $GITHUB_STEP_SUMMARY

          echo "## cluster-layers" >> $GITHUB_STEP_SUMMARY
          cat tests/cluster-layers/terrabuild-debug.md >> $GITHUB_STEP_SUMMARY

          echo "## multirefs" >> $GITHUB_STEP_SUMMARY
          cat tests/multirefs/terrabuild-debug.md >> $GITHUB_STEP_SUMMARY

          echo "## simple" >> $GITHUB_STEP_SUMMARY
          cat tests/simple/terrabuild-debug.md >> $GITHUB_STEP_SUMMARY

          echo "## indirect-target" >> $GITHUB_STEP_SUMMARY
          cat tests/indirect-target/terrabuild-debug.md >> $GITHUB_STEP_SUMMARY

      - name: Upload Terrabuild Debug
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Terrabuild Debug
          path: |
            **/terrabuild-debug.*
