name: prepare-release
run-name: Prepare release ${{github.ref_name}}

on:
  push:
    tags:
      - '**'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.302

      - name: Build & Publish
        run: make dist-all config=Release version=${{github.ref_name}}

      - name: GitHub Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          draft: true
          generate_release_notes: true
          files: |
            ./.out/*.zip
            ./.out/*.nupkg
