name: prepare-release
run-name: Prepare release ${{github.ref_name}}

on:
  push:
    tags:
      - '**'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.302

      - name: Extract Version/Version Suffix
        run: |
          s=${{github.ref_name}}
          pat="([^-]*)-?([^-]*)"
          [[ $s =~ $pat ]]
          BUILD_VERSION=${BASH_REMATCH[1]}
          BUILD_VERSION_SUFFIX=${BASH_REMATCH[2]}
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo "BUILD_VERSION_SUFFIX=$BUILD_VERSION_SUFFIX" >> $GITHUB_ENV
          echo "BUILD_VERSION: $BUILD_VERSION"
          echo "BUILD_VERSION_SUFFIX: $BUILD_VERSION_SUFFIX"

      - name: Add Cert to Keychain
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.MAC_CERT_BASE64 }}
          p12-password: ${{ secrets.MAC_CERT_PASSWORD }}

      - name: Build & Publish
        run: make dist-all config=Release version=${{ env.BUILD_VERSION }} version_suffix=${{ env.BUILD_VERSION_SUFFIX }}

      - name: Notarize
        uses: GuillaumeFalourd/notary-tools@v1
        with:
          product_path: ".out/terrabuild-darwin-x64.zip" # or .pkg or .dmg
          apple_id: ${{ secrets.MAC_DEV_LOGIN }}
          password: ${{ secrets.MAC_DEV_PASSWORD }}
          team_id: ${{ secrets.MAC_DEV_TEAM_ID }}
          xcode_path: '/Applications/Xcode_15.3.app'

      - name: GitHub Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          draft: true
          prerelease: ${{ env.BUILD_VERSION_SUFFIX != '' }}
          generate_release_notes: true
          files: |
            ./.out/*.zip
            ./.out/*.nupkg
