name: prepare-release
run-name: Prepare release ${{github.ref_name}}

on:
  push:
    tags:
      - '**'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.302

      - name: Extract Version/Version Suffix
        run: |
          s=${{github.ref_name}}
          pat="([^-]*)-?([^-]*)"
          [[ $s =~ $pat ]]
          BUILD_VERSION=${BASH_REMATCH[1]}
          BUILD_VERSION_SUFFIX=${BASH_REMATCH[2]}
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo "BUILD_VERSION_SUFFIX=$BUILD_VERSION_SUFFIX" >> $GITHUB_ENV
          echo "BUILD_VERSION: $BUILD_VERSION"
          echo "BUILD_VERSION_SUFFIX: $BUILD_VERSION_SUFFIX"

      - name: Build & Publish
        run: make publish-all config=Release version=${{ env.BUILD_VERSION }} version_suffix=${{ env.BUILD_VERSION_SUFFIX }}

      - name: Pack
        run: |
          (cd .out/dotnet; zip ../terrabuild-dotnet.zip ./*)
          (cd .out/windows; zip ../terrabuild-windows-x64.zip ./terrabuild.exe)
          (cd .out/linux; zip ../terrabuild-linux-x64.zip ./terrabuild)
          (cd .out/darwin; zip -r ../terrabuild-darwin-binaries.zip .)

      - name: Archive .net Outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs-dotnet
          include-hidden-files: true
          path: .out/terrabuild-dotnet.zip

      - name: Archive NuGet Outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs-nuget
          include-hidden-files: true
          path: .out/*.nupkg

      - name: Archive Windows Outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs-windows
          include-hidden-files: true
          path: .out/terrabuild-windows-x64.zip

      - name: Archive Linux Outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs-linux
          include-hidden-files: true
          path: .out/terrabuild-linux-x64.zip

      - name: Archive macOS outputs
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-macos
          include-hidden-files: true
          path: |
            .out/terrabuild-darwin-binaries.zip
            entitlements.plist

  sign:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download macOS outputs
        uses: actions/download-artifact@v4
        with:
          name: unsigned-macos

      - name: Extract Binaries
        run: unzip -d .out/darwin .out/terrabuild-darwin-binaries.zip

      - name: Add Cert to Keychain
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.MAC_CERT_BASE64 }}
          p12-password: ${{ secrets.MAC_CERT_PASSWORD }}

      - name: Sign Binaries
        run: |
          codesign --force --timestamp --sign "Developer ID Application: Magnus Opera (${{ secrets.MAC_DEV_TEAM_ID }})" .out/darwin/x64/terrabuild --options=runtime --no-strict --entitlements entitlements.plist
          codesign --force --timestamp --sign "Developer ID Application: Magnus Opera (${{ secrets.MAC_DEV_TEAM_ID }})" .out/darwin/arm64/terrabuild --options=runtime --no-strict --entitlements entitlements.plist
          lipo -create -output .out/darwin/terrabuild .out/darwin/x64/terrabuild .out/darwin/arm64/terrabuild
          codesign --force --timestamp --sign "Developer ID Application: Magnus Opera (${{ secrets.MAC_DEV_TEAM_ID }})" .out/darwin/terrabuild --options=runtime --no-strict --entitlements entitlements.plist
          (cd .out/darwin; zip ../terrabuild-darwin-universal.zip ./terrabuild)

      - name: Archive Signed Binaries
        uses: actions/upload-artifact@v4
        with:
          name: outputs-macos
          include-hidden-files: true
          path: .out/terrabuild-darwin-universal.zip

  create-release:
    runs-on: ubuntu-latest
    needs: sign
    steps:
      - name: Download outputs
        uses: actions/download-artifact@v4
        with:
          pattern: outputs-*
          merge-multiple: true
          path: .out

      - name: Extract Version/Version Suffix
        run: |
          s=${{github.ref_name}}
          pat="([^-]*)-?([^-]*)"
          [[ $s =~ $pat ]]
          BUILD_VERSION=${BASH_REMATCH[1]}
          BUILD_VERSION_SUFFIX=${BASH_REMATCH[2]}
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo "BUILD_VERSION_SUFFIX=$BUILD_VERSION_SUFFIX" >> $GITHUB_ENV
          echo "BUILD_VERSION: $BUILD_VERSION"
          echo "BUILD_VERSION_SUFFIX: $BUILD_VERSION_SUFFIX"

      - name: GitHub Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          draft: true
          prerelease: ${{ env.BUILD_VERSION_SUFFIX != '' }}
          generate_release_notes: true
          files: |
            .out/*.zip
            .out/*.nupkg

      - uses: geekyeggo/delete-artifact@v5.1.0
        with:
            name: "*"
