name: prepare-release
run-name: Prepare release ${{github.ref_name}}

on:
  push:
    tags:
      - '**'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.302

      - name: Extract Version/Version Suffix
        run: |
          s=${{github.ref_name}}
          pat="([^-]*)-?([^-]*)"
          [[ $s =~ $pat ]]
          BUILD_VERSION=${BASH_REMATCH[1]}
          BUILD_VERSION_SUFFIX=${BASH_REMATCH[2]}
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo "BUILD_VERSION_SUFFIX=$BUILD_VERSION_SUFFIX" >> $GITHUB_ENV
          echo "BUILD_VERSION: $BUILD_VERSION"
          echo "BUILD_VERSION_SUFFIX: $BUILD_VERSION_SUFFIX"

      - name: Build & Publish
        run: make publish-all config=Release version=${{ env.BUILD_VERSION }} version_suffix=${{ env.BUILD_VERSION_SUFFIX }}

      - name: Pack
        run: |
          (cd .out/dotnet; zip -u ../dotnet.zip ./*)
          (cd .out/windows; zip -u ../terrabuild-windows-x64.zip ./terrabuild.exe)
          (cd .out/linux; zip -u ../terrabuild-linux-x64.zip ./terrabuild)

      - name: Archive outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          include-hidden-files: true
          path: |
            .out/*.zip
            .out/*.nupkg

      - name: Archive macOS outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs-macos
          include-hidden-files: true
          path: |
            .out/darwin/
            entitlements.plist

  sign:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download macOS outputs
        uses: actions/download-artifact@v4
        with:
          name: outputs-macos

      - name: Dump
        run: ls -alR .

      - name: Add Cert to Keychain
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.MAC_CERT_BASE64 }}
          p12-password: ${{ secrets.MAC_CERT_PASSWORD }}

      - name: Sign
        run: |
          codesign --force --timestamp --sign "Developer ID Application: Magnus Opera (${{ secrets.MAC_DEV_TEAM_ID }})" .out/darwin/x64/terrabuild --options=runtime --no-strict --entitlements entitlements.plist
          codesign --force --timestamp --sign "Developer ID Application: Magnus Opera (${{ secrets.MAC_DEV_TEAM_ID }})" .out/darwin/arm64/terrabuild --options=runtime --no-strict --entitlements entitlements.plist
          lipo -create -output .out/darwin/terrabuild .out/darwin/x64/terrabuild .out/darwin/arm64/terrabuild
          (cd .out/darwin; zip -u ../terrabuild-darwin-universal.zip ./terrabuild)

      - name: Archive signed outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs-macos-signed
          include-hidden-files: true
          path: .out/darwin/*.zip

  create-release:
    runs-on: ubuntu-latest
    needs: sign
    steps:
      - name: Download outputs
        uses: actions/download-artifact@v4
        with:
          name: outputs

      - name: Download macOS outputs
        uses: actions/download-artifact@v4
        with:
          name: outputs-macos-signed

      - name: Extract Version/Version Suffix
        run: |
          s=${{github.ref_name}}
          pat="([^-]*)-?([^-]*)"
          [[ $s =~ $pat ]]
          BUILD_VERSION=${BASH_REMATCH[1]}
          BUILD_VERSION_SUFFIX=${BASH_REMATCH[2]}
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo "BUILD_VERSION_SUFFIX=$BUILD_VERSION_SUFFIX" >> $GITHUB_ENV
          echo "BUILD_VERSION: $BUILD_VERSION"
          echo "BUILD_VERSION_SUFFIX: $BUILD_VERSION_SUFFIX"

      - name: GitHub Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          draft: true
          prerelease: ${{ env.BUILD_VERSION_SUFFIX != '' }}
          generate_release_notes: true
          files: |
            .out/*.zip
            .out/*.nupkg
