name: release

on:
  push:
    branches:
      - 'releases/**'

    tags:
      - 'v**'

env:
  TERRABUILD_AZURE_BLOB_STORAGE: ${{ secrets.TERRABUILD_AZURE_BLOB_STORAGE }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write    

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.100

      - name: Build & Publish
        run: make dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            LICENSE
            ./.out/windows/Terrabuild.exe
            ./.out/macos/Terrabuild
            ./.out/linux/Terrabuild
            ./.out/dotnet/Terrabuild
