name: release

on:
  release:
    types: [released]

jobs:
  release-nuget:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.204

      - name: Download Github Release artifacts
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          version: ${{github.ref_name}}
          file: '*'

      - name: NuGet Release
        run: dotnet nuget push ./Terrabuild.${{github.ref_name}}.nupkg --skip-duplicate --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
