name: build

on:
  push:
    branches:
      - 'releases/**'

    tags:
      - 'v**'

env:
  TERRABUILD_AZURE_BLOB_STORAGE: ${{ secrets.TERRABUILD_AZURE_BLOB_STORAGE }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write    

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.100

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish
        run: make self-publish

      - name: Upload Terrabuild Debug
        uses: actions/upload-artifact@v4
        with:
          name: Terrabuild Debug
          path: terrabuild.*.json
