name: release
run-name: Release ${{github.ref_name}}

on:
  workflow_dispatch:
  release:
    types: [released]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.204

      - name: Download Github Release artifacts
        uses: robinraju/release-downloader@v1.10
        with:
          tag: ${{github.ref_name}}
          fileName: '*'

      - name: NuGet Release
        run: dotnet nuget push ./Terrabuild.${{github.ref_name}}.nupkg --skip-duplicate --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
