name: 🦄 Self Build

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: version
        default: latest
      prerelease:
        type: boolean
        description: use Terrabuild prerelease
        default: false
      retry:
        type: boolean
        description: retry failed tasks
        default: false
      force:
        type: boolean
        description: force build

env:
  TERRABUILD_API_URL: https://api.dev.magnusopera.io

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "dev"

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Install Terrabuild
        uses: magnusopera/action-install-gh-release@feature/prerelease
        with:
          repo: magnusopera/terrabuild
          tag: ${{ inputs.version }}
          prerelease: ${{ inputs.prerelease }}

      - name: Login to Space
        run: |
          terrabuild version
          terrabuild login --workspace edd11090a41b0291301431d0 --token ${{ secrets.TERRABUILD_TOKEN }}

      - name: Build
        run: |
          terrabuild run build test \
            --log --debug \
            -c "dev" \
            ${{ github.event.inputs.force == 'true' && '--force' || '' }} \
            ${{ inputs.retry == true && '--retry' || '' }} \
            ${{ github.run_attempt > 1 && '--retry' || '' }}

      - name: Upload Terrabuild Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: terrabuild-dev-self-build-${{ github.sha }}
          path: |
            terrabuild-debug.*
            ~/.terrabuild/cache/**/status
            ~/.terrabuild/cache/**/summary.json
            ~/.terrabuild/cache/**/*.log

      - name: Create Test Report
        uses: magnusopera/test-reporter@main
        if: always()
        with:
          name: Unit Tests Report
          path: '**/*.trx'
          reporter: dotnet-trx
          fail-on-empty: false
          use-actions-summary: true
