name: 🦄 Self Build
run-name: "${{ github.name }} ${{ inputs.retry == true && 'retry' || '' }} ${{ inputs.force == true && 'force' || '' }}"

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: force build
      version:
        type: string
        description: version
        default: latest

env:
  TERRABUILD_API_URL: https://api.dev.magnusopera.io

permissions:
  contents: read
  packages: write    
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "dev"

    steps:
      - name: Info
        run: echo 'Building ${{ github.ref }}'

      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.102

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Terrabuild
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          token: ${{ secrets.MAGNUSOPERA_CONTENT_TOKEN }}
          repo: magnusopera/terrabuild
          platform: linux
          tag: ${{ inputs.version }}

      - name: Login to Space
        run: terrabuild login --space magnusopera/terrabuild --token ${{ secrets.TERRABUILD_TOKEN }}

      - name: Build
        run: |
          echo 'Building ${{ github.ref }}'
          terrabuild version
          terrabuild run build test \
            --logs --debug \
            -w src \
            -c "dev" \
            ${{ github.event.inputs.force == 'true' && '--force' || '' }} \
            ${{ github.run_attempt > 1 && '--retry' || '' }}

      - name: Upload Terrabuild Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: terrabuild-dev-self-build-${{ github.sha }}
          path: |
            terrabuild-debug.*
            ~/.terrabuild/buildcache/**/status
            ~/.terrabuild/buildcache/**/summary.json
            ~/.terrabuild/buildcache/**/*.log

      - name: Create Test Report
        uses: magnusopera/test-reporter@main
        if: always()
        with:
          name: Unit Tests Report
          path: '**/*.trx'
          reporter: dotnet-trx
          fail-on-empty: false
          use-actions-summary: true
